### ISSUE TITLE
Unit_hipMemsetAsync_QueueJobsMultithreaded causes a node crash 

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#241] opened 2022-11-03 06:20 UTC
Tested on Gen9 and ATS. Must be run for a while. This might have something to do with deadlock detection on JLSE.

**Comment by pvelesko** [comment] 2022-11-03 06:20
@Sarbojit2019 Can you please run this test on Intel systems for a while to confirm that it works for you?

**Comment by Sarbojit2019** [comment] 2022-11-04 07:29
@pvelesko, I have tested this with latest chip-spv::main (branch) on ATS. I could successfully run 500 iteration for Level0 and Opencl.

**Comment by Sarbojit2019** [comment] 2022-12-12 10:03
I am closing the ticket as I am not able to reproduce the issue with latest. Feel free to reopen in case required.

**Closed by Sarbojit2019** 2022-12-12 10:03 UTC
Labels: level0, opencl
