### ISSUE TITLE
Implementation of Math intrinsics is not portable

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/chip-spv#222] opened 2022-10-26 13:29 UTC
The current implementation maps [CUDA intrinsics](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__SINGLE.html#group__CUDA__MATH__INTRINSIC__SINGLE) to OpenCL [native_ functions](https://registry.khronos.org/OpenCL/sdk/1.0/docs/man/xhtml/mathFunctions.html).

The CUDA intrinsics' accuracy is [well defined](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#intrinsic-functions), whereas the OpenCL native functions can be pretty much whatever and the accuracy of the implementation cannot be queried from the device. Calling the native functions and assuming CUDA accuracy when doing so makes the generated SPIR-V inherently non-portable. The native functions could just return zero or even rand() and be compliant as far as I understand.

This problem can be demonstrated with the cuda-blackscholes test case (#142): It works (by good enough implementation accuracy) with the iGPU, but fails with the CPU. When I force it to use an accurate version of fexp, it works similarly with GPU and CPU.

This means, unfortunately, that we cannot use the native versions for implementing the intrinsics by default. I'm not sure what the best fix would be to gain the performance benefits of the faster "native" intrinsics when it's safe to do so. Probably via an SPIR-V extension that can be used to declare/demand at least similar accuracy that CUDA defines to the "native" versions or such.

**Comment by pvelesko** [comment] 2022-10-26 13:41
Could this be solved by using OCML instead of native opencl functions?

**Comment by bashbaug** [comment] 2022-10-27 20:24
I don't think it makes sense to try to bound the accuracy of the "native" built-in functions.  The "native" functions are intended to map as closely as possible to underlying hardware instructions, so by definition their error bounds will be implementation-defined.

I do think it would be interesting to consider another class of built-in functions, say "fast" built-in functions, with defined error bounds, but not necessarily a 1:1 mapping to native hardware instructions.

Note that OpenCL C 2.0 and newer already defined error bounds for a large set of commonly-used built-in functions (see [link](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_C.html#table-float-ulp-relaxed), and the [equivalent in SPIR-V](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Env.html#_ulp_values_for_math_instructions_unsafe_math_optimizations_enabled)).  If this set of built-in functions and the defined error bounds are sufficient then I think this would be a great place to start from.

**Comment by pjaaskel** [comment] 2022-10-28 07:45
Unfortunately the CUDA intrinsics seem to be (often very slightly) more accurate than the relaxed mode requires so we cannot use that as a reference point for the new extension. Needs more consideration.

**Comment by pvelesko** [comment] 2023-05-06 18:49
https://intel.github.io/llvm-docs/cuda/cuda-vs-opencl-math-builtin-precisions.html 

for example, cos() is ≤ 4 ulp and 2 ulp for CUDA

my question is, do we need to match the accuracy? If so, is there an equivalent library with more precise implementations available? similar to OCML? 

Speaking of OCML, it seems that their accuracy is similar to that of OpenCL. 

Would it make sense to have 3 levels of accuracy? CUDA-precision, OCML/OpenCL, and OpenCL native_ ?

**Comment by pjaaskel** [comment] 2023-05-08 12:03
Yep, we need to match the accuracy demands for correctness. I'd focus first on CUDA/HIP compatibility and then add the other modes with reduced accuracy, if wanted. That basically adds a new CHIP-SPV-only build mode which is not CUDA nor HIP compatible?

**Comment by pjaaskel** [comment] 2023-05-08 12:54
> > Yep, we need to match the accuracy demands for correctness
> 
> How do we do that? Is there a target agnostic math library implementation that can achieve the correctness that CUDA demands?

I do not know, I haven't searched. The current idea is to define a new OpenCL extension for defined-accuracy intrinsics calls and then let the drivers map to whatever they can.

> > I'd focus first on CUDA/HIP compatibility and then add the other modes with reduced accuracy, if wanted.
> 
> Well we have the other modes available already it's the CUDA precision that we're lacking.

The current one should fulfil the CUDA precision, but yep doesn't benefit from the reduced-accuracy.

**Comment by pvelesko** [comment] 2023-05-08 13:01
Cuda requires 2 ulp for a lot of functions whereas OpenCL and OCML max out at 4. Is that not an issue?

**Comment by pjaaskel** [comment] 2023-05-08 13:31
Ah, sorry, I thought you were talking about the intrinsics vs. native_*. Indeed that is an issue if even the most accurate ones do not deliver enough accuracy. I've missed that.

**Comment by pjaaskel** [comment] 2023-05-08 15:17
Let's at least document this.

**Comment by pvelesko** [comment] 2023-05-08 15:18
duplicate of #428  @pjaaskel

**Closed** 2023-05-09 12:04 UTC
Labels: enhancement
