### ISSUE TITLE
samples/hip-cuda/FloydWarshall uses a lot of memory with Level0 backend

### ISSUE THREAD

**Issue by franz** [CHIP-SPV/chip-spv#101] opened 2022-08-10 15:58 UTC
seems like a memory leak of some kind, the test uses >20G memory with Level0 backend, with OpenCL backend it runs in ~135M or so.

**Comment by pvelesko** [comment] 2022-08-11 05:16
duplicate of  #74, I believe

**Comment by pvelesko** [comment] 2022-08-11 06:43
Any other tests that time out for you?

**Comment by linehill** [comment] 2022-08-11 09:20
Took a peek into the FloydWarshall issue. Valgrind suggests that we are leaking command lists. That seems to be the case because the refcounts of events associated with the command list never seem to decrease to zero which is a condition for `CHIPCallbackEventMonitorLevel0::monitor()` to delete the command list.

**Comment by pvelesko** [comment] 2022-08-11 12:15
I think it's because it's doing a 3D memcopy which is implemented by calling regular hipMemcpy which results in a huge number of command lists being created. That's why I asked if any other tests are timing out for you - I think the 3D mem copy tests have the same issue.

**Comment by franz** [comment] 2022-08-11 13:38
BitonicSort is another, although it's not as bad as FloydWarshall, it's using "only" about 7.5GB (when run with cmake test arguments).

As for 3D memcopy, i don't see it anywhere in the FloydWarshall code or the BitonicSort, they only use regular hipMemcpy. But both tests create a large number of kernel launches (256 per algorithm iteration in FloydWarshall). So its possible the underlying issue is the same (lots of command lists not freed) but this needs to be fixed in the backend, not the user code.

**Comment by linehill** [comment] 2022-08-12 06:11
FYI, attempted to fix the issue with #103. Got memory hogging fixed with it but other issues appear.

**Closed** 2022-08-12 14:07 UTC
